In [3]:
import numpy as np

#help(np)

In [4]:
array1 = np.array([1, 2, 3, 4])

print(array1)
print(type(array1))
print(array1.shape)
print(array1.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
1


In [5]:
array2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ])

print(array2)
print(type(array2))
print(array2.shape)
print(array2.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
(4, 3)
2


In [6]:
array2[0:2 , 0:1]

array([[1],
       [4]])

In [7]:
array2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array2[0: , 1:2]

array([[ 2],
       [ 5],
       [ 8],
       [11]])

In [9]:
array2[1: , 1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [10]:
array2[0]

array([1, 2, 3])

In [11]:
array2[0][1]

2

In [12]:
array2[0][1] = 20
array2

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
array2[0] = [10, 20, 30]
array2

array([[10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
a = array2.reshape(12, )

print(a)
print(a.shape)
print(a.ndim)

[10 20 30  4  5  6  7  8  9 10 11 12]
(12,)
1


In [15]:
b = array2.reshape(3, 4)

print(b)
print(b.shape)

[[10 20 30  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [16]:
c = array2.reshape(6, 2)

print(c)
print(c.shape)

[[10 20]
 [30  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(6, 2)


In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones([8, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
d = np.eye(4)

print(d)
print(d.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [22]:
np.full([4, 5], 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [23]:
np.linspace(1, 10, 10) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.linspace(2, 8, 5) 

array([2. , 3.5, 5. , 6.5, 8. ])

In [25]:
np.random.random([2, 4])

array([[0.1766713 , 0.42659854, 0.24858737, 0.30815281],
       [0.29323496, 0.59772719, 0.24355845, 0.84942658]])

In [26]:
array4 = np.array([ [6, 18, 12], [8, 14, 1], [12, 22, 4], [10, 3, 6] ])

array4

array([[ 6, 18, 12],
       [ 8, 14,  1],
       [12, 22,  4],
       [10,  3,  6]])

In [27]:
array4.min()

1

In [28]:
array4.max()

22

In [29]:
array4.argmin()

5

In [30]:
array4.argmax()

7

In [31]:
array4.mean()

9.666666666666666

In [32]:
array4.std()

6.004627844883941

In [33]:
array4.sum()

116

In [34]:
array4

array([[ 6, 18, 12],
       [ 8, 14,  1],
       [12, 22,  4],
       [10,  3,  6]])

In [35]:
array4[0: , 1:2]

array([[18],
       [14],
       [22],
       [ 3]])

In [36]:
array4[0: , 1:2].sum()

57

In [37]:
array4[1:3, 1:]

array([[14,  1],
       [22,  4]])

In [38]:
array4[1:3, 1:].sum()

41

In [39]:
array4

array([[ 6, 18, 12],
       [ 8, 14,  1],
       [12, 22,  4],
       [10,  3,  6]])

In [40]:
array4.T

array([[ 6,  8, 12, 10],
       [18, 14, 22,  3],
       [12,  1,  4,  6]])

In [41]:
e = np.arange(10, 20)
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
f = np.arange(10, 20, 2)
f

array([10, 12, 14, 16, 18])

In [43]:
g = np.random.uniform(1, 10, [3, 4])

print(g.shape)
print(g)
print("\n")
print(g.reshape([6, 2]))

(3, 4)
[[2.83658379 5.18357007 3.76182424 2.43287666]
 [7.31660798 1.64804492 8.76554077 7.59109708]
 [2.32758506 3.06097462 9.51632432 8.38977823]]


[[2.83658379 5.18357007]
 [3.76182424 2.43287666]
 [7.31660798 1.64804492]
 [8.76554077 7.59109708]
 [2.32758506 3.06097462]
 [9.51632432 8.38977823]]


In [44]:
array5 = np.array([ [8, 12, 20], [4, 42, 16], [32, 64, 9] ])

In [45]:
array5

array([[ 8, 12, 20],
       [ 4, 42, 16],
       [32, 64,  9]])

In [46]:
np.divide(array5, 2)

array([[ 4. ,  6. , 10. ],
       [ 2. , 21. ,  8. ],
       [16. , 32. ,  4.5]])

In [47]:
np.abs(array5)

array([[ 8, 12, 20],
       [ 4, 42, 16],
       [32, 64,  9]])

In [48]:
np.all(array5 >= 4)

True

In [49]:
np.all(array5 == 4)

False

In [50]:
np.any(array5 == 4)

True

In [51]:
np.any(array5 >= 10 )

True

In [52]:
np.any(array5 >= 100 )

False

In [53]:
np.min(array5)

4

In [54]:
np.max(array5)

64

In [55]:
np.argmin(array5)

3

In [56]:
np.argmax(array5)

7

In [57]:
np.sin(array5)

array([[ 0.98935825, -0.53657292,  0.91294525],
       [-0.7568025 , -0.91652155, -0.28790332],
       [ 0.55142668,  0.92002604,  0.41211849]])

In [58]:
np.cos(array5)

array([[-0.14550003,  0.84385396,  0.40808206],
       [-0.65364362, -0.39998531, -0.95765948],
       [ 0.83422336,  0.39185723, -0.91113026]])

In [59]:
np.sqrt(array5)

array([[2.82842712, 3.46410162, 4.47213595],
       [2.        , 6.4807407 , 4.        ],
       [5.65685425, 8.        , 3.        ]])

In [60]:
np.average(array5)

23.0

In [61]:
array5

array([[ 8, 12, 20],
       [ 4, 42, 16],
       [32, 64,  9]])

In [62]:
np.average(array5, axis=0)

array([14.66666667, 39.33333333, 15.        ])

In [63]:
np.average(array5, axis=1)

array([13.33333333, 20.66666667, 35.        ])

In [64]:
np.sum(array5)

207

In [65]:
array5

array([[ 8, 12, 20],
       [ 4, 42, 16],
       [32, 64,  9]])

In [66]:
np.sum(array5, axis=0)

array([ 44, 118,  45])

In [67]:
np.sum(array5, axis=1)

array([ 40,  62, 105])

In [68]:
np.median(array5)

16.0

In [69]:
np.ndim(array5)

2

In [70]:
array5

array([[ 8, 12, 20],
       [ 4, 42, 16],
       [32, 64,  9]])

In [71]:
np.sort(array5, axis=0)

array([[ 4, 12,  9],
       [ 8, 42, 16],
       [32, 64, 20]])

In [72]:
np.sort(array5, axis=1)

array([[ 8, 12, 20],
       [ 4, 16, 42],
       [ 9, 32, 64]])

In [73]:
a = np.array([[8, 2, 12], [4, 15, 2]])
b = np.array([[10, 20, 18], [14, 22, 6]])

In [74]:
a

array([[ 8,  2, 12],
       [ 4, 15,  2]])

In [75]:
b

array([[10, 20, 18],
       [14, 22,  6]])

In [76]:
a+b

array([[18, 22, 30],
       [18, 37,  8]])

In [77]:
b-a

array([[ 2, 18,  6],
       [10,  7,  4]])

In [78]:
a*b

array([[ 80,  40, 216],
       [ 56, 330,  12]])

In [79]:
b/a

array([[ 1.25      , 10.        ,  1.5       ],
       [ 3.5       ,  1.46666667,  3.        ]])

In [80]:
a

array([[ 8,  2, 12],
       [ 4, 15,  2]])

In [81]:
b

array([[10, 20, 18],
       [14, 22,  6]])

In [82]:
np.vstack( (a, b) )

array([[ 8,  2, 12],
       [ 4, 15,  2],
       [10, 20, 18],
       [14, 22,  6]])

In [83]:
np.hstack((a, b))

array([[ 8,  2, 12, 10, 20, 18],
       [ 4, 15,  2, 14, 22,  6]])

In [84]:
a

array([[ 8,  2, 12],
       [ 4, 15,  2]])

In [85]:
for i in a:
    print( i )

[ 8  2 12]
[ 4 15  2]


In [86]:
L1 = []
for i in a:
    for j in i:
        L1.append(j)

In [87]:
print(L1)
print(type(L1))

[8, 2, 12, 4, 15, 2]
<class 'list'>


In [88]:
a

array([[ 8,  2, 12],
       [ 4, 15,  2]])

In [89]:
for idx, x in np.ndenumerate(a):
    print(idx, x)

(0, 0) 8
(0, 1) 2
(0, 2) 12
(1, 0) 4
(1, 1) 15
(1, 2) 2
